version: "3.8"

# RAFT Cluster
services:
  node-0:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-0
    restart: unless-stopped
    hostname: ${SERVER_HOSTNAME_0}
    ports:
      - 8080:${SERVER_PORT_0}
    environment:
      - SERVER_HOSTNAME=${SERVER_HOSTNAME_0}
      - SERVER_PORT=${SERVER_PORT_0}
    volumes:
      - ./server:/usr/src/app
      - node-0:/mnt
    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  node-0:
    driver: local
