version: "3.8"

# RAFT Cluster
services:
  node-0:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-0
    restart: unless-stopped
    hostname: node-0-server
    ports:
      - 8080:8080
    volumes:
      - ./server:/usr/src/app
      - node-0:/mnt
    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  node-0:
    driver: local
