version: "3.8"

# RAFT Cluster
services:
  node-1:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: node-1
    restart: unless-stopped
    hostname: node-1-server
    volumes:
      - ./server:/app
    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge
